language: rust
cache: cargo
rust: nightly

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-trusty-6.0
    packages:
      # install deps
      - libelf-dev
      - lib32z1-dev
      - libedit-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - libssl-dev
      # and install LLVM itself
      - llvm-6.0-dev

before_install:
  - export LLVM_VERSION="6.0"
  - export LLVM_VERSION_DASH=${LLVM_VERSION/./-}
  - export LLVM_VERSION_SHORT=${LLVM_VERSION/./}
  - export LLVM_DIR=/usr/lib/llvm-${LLVM_VERSION}/bin/
  - export PATH=$LLVM_DIR:$HOME/.local/bin:$PATH
  - export LLVM_PATH=/usr/share/llvm-${LLVM_VERSION}/cmake/
  - export | grep LLVM
  - ls $LLVM_DIR
  - ls $LLVM_PATH

script:
  - set -ex
  - cargo build --all --verbose
  - cargo test --all --verbose

before_deploy:
  - cargo doc --all
  - echo '<head><meta http-equiv="refresh" content="0; URL=mcc/index.html" /></head>' > target/doc/index.html

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/doc
  on:
    branch: master

env:
  global:
    secure: svTCNx+2v02qcKVQ6zHnyb9vVy6ohtkOF7jEHD2DnWvIbtuwt9pA0fUiinWatohCsB0Ako2LgzVe2Sirwwcf8InwHIUsrLEKzpaevpEogbD81GzeyhoCeQVaE5wZZQXfBsFtPWkbIQ72poYX5xU3D/OlOkSrxP6WTNow1i6wIWJjdVVV24NB7N7e26hU2d3v0O5pR8t59CWef1AiLVweRjMJfKbK7uc6fiuYUU6YH2iBqRwtES+lbp69B49RaBATF619MgxClCiVxAe3nkvG4b2MqZgLhcFqRrxUsPiYhFYsZU68iD9MPvZ+6mv1m+cB6c7kgJyEougJdJ6+Re9bYeID5sxO3hAHNea2xo16vP7OQY+TrfrQ4yOGeehrTTBA+/mSLFyX2J8ecZkwOsCq+6Gu+Zs6YKRwxZ4sxU+7EdqQMqvIzUjDPXxHsOiSxe1+Ij8tuMMmTg6GOelR/etmEp1ZzC0TgbOUkuadYb7VvKxQEi6msRV/UapYr9UoHF5Fk0Nq+r4gRiWF6f8ZONMDGhmL3K9YWqG9EgEg2lkHIiIHbe+ncaViOVhQm265OGzBhk76SqVwSDW2O77FNUHnT0zcw3+NumhGqq0HM2xjm3C3/+P3jc1D/5KhmmG43doH8WYVTR2NLMk+iM+U2dmMnEVqUZFBMAAZFP6ncMc0DVA=

after_success: |
  RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
  cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

