// Generated by `error_codes`. DO NOT EDIT!

//! Common error codes used across the compiler.
#![allow(non_upper_case_globals)]
use codespan_reporting::diagnostic::Severity;
#[derive(Debug, Clone, PartialEq, Eq, Ord, PartialOrd, Hash)]
pub struct ErrorCode {
    pub segments: &'static [&'static str],
    pub severity: Severity,
    pub description: &'static str,
}
impl ErrorCode {
    /// The fully qualified path of the error code.
    pub fn path(&self) -> impl std::fmt::Display + '_ {
        std::fmt::from_fn(|f| {
            for (i, segment) in self.segments.iter().enumerate() {
                if i > 0 {
                    write!(f, "::")?;
                }
                write!(f, "{}", segment)?;
            }
            Ok(())
        })
    }
}
impl std::fmt::Display for ErrorCode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let ErrorCode {
            severity,
            description,
            ..
        } = self;
        let path = self.path();
        write!(f, "{severity:?}[{path}]: {description}")
    }
}
/// All error codes.
pub const ALL: &[ErrorCode] = &[
    parse::invalid_type,
    parse::keyword_as_identifier,
    parse::missing_token,
    parse::unexpected_token,
    type_check::invalid_lvalue,
    type_check::invalid_type,
    type_check::keyword_as_identifier,
    type_check::missing_return_type,
    type_check::redefinition,
    type_check::undeclared_identifier,
    type_check::unimplemented,
];
/// The error codes definition, as YAML.
pub const DEFINITION: &str = include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/error-codes.yaml"));
pub mod parse {
    use super::*;
    ///Invalid or unsupported type specifier.
    pub const invalid_type: ErrorCode = ErrorCode {
        segments: &["parse", "invalid_type"],
        severity: Severity::Error,
        description: "Invalid or unsupported type specifier.",
    };
    ///A C keyword was used as an identifier.
    pub const keyword_as_identifier: ErrorCode = ErrorCode {
        segments: &["parse", "keyword_as_identifier"],
        severity: Severity::Error,
        description: "A C keyword was used as an identifier.",
    };
    ///The parser expected a token but found none.
    pub const missing_token: ErrorCode = ErrorCode {
        segments: &["parse", "missing_token"],
        severity: Severity::Error,
        description: "The parser expected a token but found none.",
    };
    ///The parser encountered an unexpected token.
    pub const unexpected_token: ErrorCode = ErrorCode {
        segments: &["parse", "unexpected_token"],
        severity: Severity::Error,
        description: "The parser encountered an unexpected token.",
    };
}
pub mod type_check {
    use super::*;
    ///Assignment to non-lvalue (invalid left-hand side).
    pub const invalid_lvalue: ErrorCode = ErrorCode {
        segments: &["type_check", "invalid_lvalue"],
        severity: Severity::Error,
        description: "Assignment to non-lvalue (invalid left-hand side).",
    };
    ///Invalid or unsupported type specifier.
    pub const invalid_type: ErrorCode = ErrorCode {
        segments: &["type_check", "invalid_type"],
        severity: Severity::Error,
        description: "Invalid or unsupported type specifier.",
    };
    ///A C keyword was used as an identifier.
    pub const keyword_as_identifier: ErrorCode = ErrorCode {
        segments: &["type_check", "keyword_as_identifier"],
        severity: Severity::Error,
        description: "A C keyword was used as an identifier.",
    };
    ///Expected a return type for function.
    pub const missing_return_type: ErrorCode = ErrorCode {
        segments: &["type_check", "missing_return_type"],
        severity: Severity::Error,
        description: "Expected a return type for function.",
    };
    ///Redefinition of variable.
    pub const redefinition: ErrorCode = ErrorCode {
        segments: &["type_check", "redefinition"],
        severity: Severity::Error,
        description: "Redefinition of variable.",
    };
    ///Use of undeclared identifier.
    pub const undeclared_identifier: ErrorCode = ErrorCode {
        segments: &["type_check", "undeclared_identifier"],
        severity: Severity::Error,
        description: "Use of undeclared identifier.",
    };
    ///This part of the type checker isn't implemented.
    pub const unimplemented: ErrorCode = ErrorCode {
        segments: &["type_check", "unimplemented"],
        severity: Severity::Bug,
        description: "This part of the type checker isn't implemented.",
    };
}
